apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: example-voting-app
build:
  local:
    push: true
  artifacts:
  - image: docker.io/{{secrets.DOCKERHUB_USERNAME}}/examplevotingapp_result
    context: result
    docker:
      dockerfile: Dockerfile

  - image: docker.io/{{secrets.DOCKERHUB_USERNAME}}/examplevotingapp_vote
    context: vote
    docker:
      dockerfile: Dockerfile
  - image: docker.io/{{secrets.DOCKERHUB_USERNAME}}/examplevotingapp_worker
    context: worker
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-specifications/*
